// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8oLGpBmHO7VBLiLlRCvZZnWgnpHJxgY',
    appId: '1:481224939964:web:13c01c7aa6a3d146c2f3b9',
    messagingSenderId: '481224939964',
    projectId: 'task-list-292d2',
    authDomain: 'task-list-292d2.firebaseapp.com',
    storageBucket: 'task-list-292d2.firebasestorage.app',
    measurementId: 'G-RZH4JLFCSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrN1sAXXpilzi9N6ELoD_J97SVCnxirU',
    appId: '1:481224939964:android:65ef6f3929952d87c2f3b9',
    messagingSenderId: '481224939964',
    projectId: 'task-list-292d2',
    storageBucket: 'task-list-292d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQf_90mmq0hA1AQw8VVuIlUTxiYE0l8k',
    appId: '1:481224939964:ios:699e5d183a5828d0c2f3b9',
    messagingSenderId: '481224939964',
    projectId: 'task-list-292d2',
    storageBucket: 'task-list-292d2.firebasestorage.app',
    iosBundleId: 'com.example.firebasetasklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQf_90mmq0hA1AQw8VVuIlUTxiYE0l8k',
    appId: '1:481224939964:ios:699e5d183a5828d0c2f3b9',
    messagingSenderId: '481224939964',
    projectId: 'task-list-292d2',
    storageBucket: 'task-list-292d2.firebasestorage.app',
    iosBundleId: 'com.example.firebasetasklist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf8oLGpBmHO7VBLiLlRCvZZnWgnpHJxgY',
    appId: '1:481224939964:web:2e11d6a65bc62f6ec2f3b9',
    messagingSenderId: '481224939964',
    projectId: 'task-list-292d2',
    authDomain: 'task-list-292d2.firebaseapp.com',
    storageBucket: 'task-list-292d2.firebasestorage.app',
    measurementId: 'G-L63DP027MP',
  );
}
